# A. NumPy


**Goal**:

* Understand the difference between one-, two- and n-dimensional arrays in NumPy;

* Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

* Understand axis and shape properties for n-dimensional arrays.

In [1]:
import numpy as np

## 1. The basics

### 1.1 An example

In [2]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [11]:
a.ndim #number of axes (dimensions)

2

In [5]:
a.dtype

dtype('int64')

In [6]:
a.dtype.name

'int64'

In [9]:
a.itemsize #the size in bytes of each element of the array

8

In [10]:
a.size #the total number of elements of the array

15

In [12]:
a.dtype.itemsize

8

In [13]:
type(a)

numpy.ndarray

In [14]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

### 1.2 Array creation

In [15]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b = np.array([2., 3, 4])
b.dtype

dtype('float64')

In [18]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
d = np.array([(1,2,3), [4.,5,6]])
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
e = np.array([[1, 2], [3., 4]], dtype=complex)
e

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
e.dtype.name

'complex128'

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones((2,3), dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [26]:
np.empty((2,3), dtype=np.int32)

array([[ 2069159998,  1074974876,  -768170609],
       [ 1074129069, -1684540248,  1073865591]], dtype=int32)

In [28]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [29]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [30]:
np.linspace(0,2,6)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [31]:
x = np.linspace(0, 2 * np.pi, 100)
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

### 1.3 Pringting arrays

In [32]:
a = np.arange(6)
print(a)
b = np.arange(12).reshape(4,3)
print(b)
c = np.arange(24).reshape(2,3,4)
print(c)
d = np.zeros((3,4)).reshape(-1,2,3)
print(d)

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [33]:
print(np.arange(100000))

[    0     1     2 ... 99997 99998 99999]


### 1.4 Basic operations

In [34]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [35]:
c = a - b
c

array([20, 29, 38, 47])

In [36]:
b**2

array([0, 1, 4, 9])

In [37]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [38]:
a < 35

array([ True,  True, False, False])

In [39]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [40]:
A * B

array([[2, 0],
       [0, 4]])

In [41]:
A @ B

array([[5, 4],
       [3, 4]])

In [42]:
B @ A

array([[2, 2],
       [3, 7]])

In [43]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [44]:
rg = np.random.default_rng(1) #create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [45]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [46]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [47]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [48]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b.dtype

dtype('float64')

In [49]:
c = a + b

In [50]:
c

array([1.        , 2.57079633, 4.14159265])

In [51]:
c.dtype

dtype('float64')

In [52]:
a.dtype

dtype('int32')

In [53]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [54]:
d.dtype

dtype('complex128')

In [55]:
a.sum()

3

In [56]:
a

array([1, 1, 1], dtype=int32)

In [57]:
a.min()

1

In [58]:
a.max()

1

In [59]:
b.max()

3.141592653589793

In [60]:
b = np.arange(12).reshape(3, 4)

In [61]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
b.sum()

66

In [63]:
b.sum(axis=0) #sum each column

array([12, 15, 18, 21])

In [64]:
b.sum(axis=1) #sum each row

array([ 6, 22, 38])

In [65]:
b.sum(axis=1, keepdims=True) #sum each row

array([[ 6],
       [22],
       [38]])

In [66]:
b.sum(axis=0, keepdims=True) #sum each column

array([[12, 15, 18, 21]])

In [70]:
b.cumsum(axis=1) #cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [71]:
b.cumsum(axis=0) #cumulative sum along each column

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

### 1.5 Universal functions

In [72]:
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [73]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [74]:
C = np.array([2., -1., 4.])
np.add(C, B)

array([2., 0., 6.])

### 1.6 Indexing, slicing and iterating

In [75]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [76]:
a[2]

8

In [77]:
a[2:5]

array([ 8, 27, 64])

In [78]:
a[:6:2]

array([ 0,  8, 64])

In [79]:
a[::-1] #reverse a

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [80]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [81]:
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [82]:
def f(x, y):
    return 10 * x + y

In [83]:
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [84]:
b[2, 3]

23

In [85]:
b[0:5, 3]

array([ 3, 13, 23, 33, 43])

In [86]:
b[:,2]

array([ 2, 12, 22, 32, 42])

In [87]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [88]:
b[-1]

array([40, 41, 42, 43])

In [89]:
c = np.array([[[0,1,2],[10,12,13]], 
              [[100, 101, 102], [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [90]:
c.shape

(2, 2, 3)

In [91]:
c[1, ...] # equal to c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [92]:
c[..., 2] # equal to c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [93]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [94]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## 2. Shape manipulation

### 2.1 Changing the shape of an array

In [95]:
a = np.floor(10 * rg.random((3,4)))
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [96]:
a.shape

(3, 4)

In [97]:
a.ravel()

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [98]:
a.reshape(6,2)

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [99]:
a.T

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [100]:
a.T.shape

(4, 3)

In [101]:
a.resize((2,6))

In [102]:
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

the `reshape` function returns its argument with a modified shape, whereas the `resize` method modifies the array itself!

In [103]:
a.reshape(-1, 4)

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [104]:
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

### 2.2 Stacking together different arrays

In [106]:
a = np.floor(10 * rg.random((2,2)))
a

array([[2., 2.],
       [7., 2.]])

In [107]:
b = np.floor(10 * rg.random((2,2)))
b

array([[4., 9.],
       [9., 7.]])

In [110]:
np.vstack((a, b)) # verticle stack

array([[2., 2.],
       [7., 2.],
       [4., 9.],
       [9., 7.]])

In [111]:
np.hstack((a, b)) # horizontal stack

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [112]:
from numpy import newaxis

In [114]:
np.column_stack((a, b)) #for 2D array, equal to hstack

array([[2., 2., 4., 9.],
       [7., 2., 9., 7.]])

In [118]:
a = np.array([4., 2.])
b = np.array([3., 5.])
np.column_stack((a, b)) #will return 2d array

array([[4., 3.],
       [2., 5.]])

In [117]:
np.hstack((a, b))

array([4., 2., 3., 5.])

In [120]:
a

array([4., 2.])

In [121]:
a[:, newaxis]

array([[4.],
       [2.]])

In [122]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 5.]])

In [123]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 5.]])

### 2.3 Splitting one array into several smaller ones

In [124]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[5., 2., 1., 9., 5., 1., 6., 7., 6., 9., 0., 5.],
       [4., 0., 6., 8., 5., 2., 8., 5., 5., 7., 1., 8.]])

In [127]:
np.hsplit(a, 3) # split into 3

[array([[5., 2., 1., 9.],
        [4., 0., 6., 8.]]),
 array([[5., 1., 6., 7.],
        [5., 2., 8., 5.]]),
 array([[6., 9., 0., 5.],
        [5., 7., 1., 8.]])]

In [128]:
np.hsplit(a, (3,4)) # split after 3 and 4 columns

[array([[5., 2., 1.],
        [4., 0., 6.]]),
 array([[9.],
        [8.]]),
 array([[5., 1., 6., 7., 6., 9., 0., 5.],
        [5., 2., 8., 5., 5., 7., 1., 8.]])]

In [129]:
np.hsplit(a, (4, 8)) # split after 4,8 columns

[array([[5., 2., 1., 9.],
        [4., 0., 6., 8.]]),
 array([[5., 1., 6., 7.],
        [5., 2., 8., 5.]]),
 array([[6., 9., 0., 5.],
        [5., 7., 1., 8.]])]

## 3. Copies and views

### 3.1 No copy at all

In [130]:
b = a
b is a

True

In [131]:
def f(x):
    print(id(x))

In [132]:
id(a)

4492249872

In [133]:
f(a)

4492249872


In [134]:
f(b)

4492249872


### 3.2 View or shallow copy

In [135]:
c = a.view()
c is a

False

In [136]:
c.base is a

True

In [137]:
f(c)

4491672144


In [139]:
id(c) == id(a)

False

In [140]:
c.flags.owndata

False

In [141]:
a.flags.owndata

True

In [142]:
b.flags.owndata

True

In [145]:
c = c.reshape((4, 6))

In [146]:
c.flags.owndata

False

In [147]:
c

array([[5., 2., 1., 9., 5., 1.],
       [6., 7., 6., 9., 0., 5.],
       [4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8.]])

In [148]:
a

array([[5., 2., 1., 9., 5., 1., 6., 7., 6., 9., 0., 5.],
       [4., 0., 6., 8., 5., 2., 8., 5., 5., 7., 1., 8.]])

In [149]:
id(c) == id(a)

False

In [150]:
s = a[:, 1:3]
s

array([[2., 1.],
       [0., 6.]])

In [151]:
s[:]=10

In [152]:
s

array([[10., 10.],
       [10., 10.]])

In [153]:
a

array([[ 5., 10., 10.,  9.,  5.,  1.,  6.,  7.,  6.,  9.,  0.,  5.],
       [ 4., 10., 10.,  8.,  5.,  2.,  8.,  5.,  5.,  7.,  1.,  8.]])

In [154]:
s.flags.owndata

False

In [155]:
a.flags.owndata

True

c is a view of the data owned by a

s[:] is a view of s

### 3.3 Deep copy

In [156]:
d = a.copy()

In [157]:
d is a

False

In [158]:
d.base is a

False

In [159]:
d.flags.owndata

True

In [160]:
d[0,0]=9
d

array([[ 9., 10., 10.,  9.,  5.,  1.,  6.,  7.,  6.,  9.,  0.,  5.],
       [ 4., 10., 10.,  8.,  5.,  2.,  8.,  5.,  5.,  7.,  1.,  8.]])

In [161]:
a

array([[ 5., 10., 10.,  9.,  5.,  1.,  6.,  7.,  6.,  9.,  0.,  5.],
       [ 4., 10., 10.,  8.,  5.,  2.,  8.,  5.,  5.,  7.,  1.,  8.]])

In [162]:
a = np.arange(int(1e8))
b = a[:100].copy()

In [163]:
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [164]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [165]:
del a

In [166]:
a

NameError: name 'a' is not defined

In [167]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [168]:
a = np.arange(int(1e8))
b = a[:100].copy()

In [169]:
a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [170]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [171]:
del a

In [172]:
a

NameError: name 'a' is not defined

In [173]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## 4. Broadcasting rules

In [175]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = b + 2
c

array([[3, 4],
       [5, 6]])

In [177]:
a = np.array([1,2])
a

array([1, 2])

In [178]:
a + b

array([[2, 4],
       [4, 6]])

In [179]:
a = np.array([[1], [2]])
a + b

array([[2, 3],
       [5, 6]])

# B. Pandas

## 1. Date table representation in Pandas

In [180]:
import pandas as pd

In [181]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)
df

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [182]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

In [183]:
ages = pd.Series([22, 35, 58], name='Age')
ages

0    22
1    35
2    58
Name: Age, dtype: int64

In [185]:
df["Age"] is ages

False

In [186]:
df["Age"].max()

58

In [187]:
df.describe()

Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

## 2. Select a subset of a DataFrame

### 2.1 Select specific columns

In [188]:
type(df["Age"])

pandas.core.series.Series

In [189]:
type(ages)

pandas.core.series.Series

In [190]:
ages.shape

(3,)

In [192]:
df["Age"].shape

(3,)

In [193]:
age_sex = df[["Age", "Sex"]]
age_sex

Age     Sex
0   22    male
1   35    male
2   58  female

In [195]:
type(age_sex)

pandas.core.frame.DataFrame

In [196]:
age_sex.shape

(3, 2)

### 2.2 Select specifi rows

In [197]:
df["Age"] > 35

0    False
1    False
2     True
Name: Age, dtype: bool

In [198]:
above_35 = df[df["Age"] > 35]
above_35

Name  Age     Sex
2  Bonnell, Miss. Elizabeth   58  female

In [199]:
above_35.shape

(1, 3)

In [200]:
age_22_35 = df[df["Age"].isin([22, 35])]
age_22_35

Name  Age   Sex
0   Braund, Mr. Owen Harris   22  male
1  Allen, Mr. William Henry   35  male

In [204]:
#equivaltent to
df[(df["Age"] == 22) | (df["Age"] == 35)]

Name  Age   Sex
0   Braund, Mr. Owen Harris   22  male
1  Allen, Mr. William Henry   35  male

### 2.3 Select specific rows and columns

In [207]:
senior_names = df.loc[df["Age"] > 30, "Name"]
senior_names # all the names with age > 30

1    Allen, Mr. William Henry
2    Bonnell, Miss. Elizabeth
Name: Name, dtype: object

In [210]:
type(senior_names)

pandas.core.series.Series

In [211]:
df.iloc[0:2,1] 

0    22
1    35
Name: Age, dtype: int64

## 3. Save

In [214]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Score": [96, 100, 74]
})
df

Name  Score
0    Alice     96
1      Bob    100
2  Charlie     74

In [215]:
df.to_csv("sample.csv", index=False)

In [216]:
df = pd.read_csv("sample.csv")
df

Name  Score
0    Alice     96
1      Bob    100
2  Charlie     74

In [217]:
df.head()

Name  Score
0    Alice     96
1      Bob    100
2  Charlie     74

In [218]:
df.describe()

Score
count    3.0
mean    90.0
std     14.0
min     74.0
25%     85.0
50%     96.0
75%     98.0
max    100.0

In [219]:
df.to_csv("sample.csv")
df = pd.read_csv("sample.csv")
df

Unnamed: 0     Name  Score
0           0    Alice     96
1           1      Bob    100
2           2  Charlie     74